services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html:cached
    environment:
      - "DB_HOST=database"
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_appwebi4.0
      MYSQL_ROOT_PASSWORD: 123Access123
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-network

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel-network

  init-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    depends_on:
      - database
    networks:
      - laravel-network
    command: sh -c " php artisan migrate --force && php artisan db:seed --force && php artisan config:cache && php artisan route:cache && php artisan view:cache "

volumes:
  dbdata:


networks:
  laravel-network:
    driver: bridge
